name: billgram
description: "gramboo sales estimation"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  fpdart: ^1.1.0
  dio: ^5.4.3+1
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/font/Urbanist-VariableFont_wght.ttf
